-- Insert itineraries for all tours
-- Tour 1: Serengeti Great Migration Safari (4 days)
INSERT INTO tour_itineraries (tour_id, day_number, title, description, activities, meals, accommodation) VALUES
(1, 1, 'Arrival in Arusha & Transfer to Serengeti', 'Fly into Kilimanjaro International Airport where your WildSmiles driver awaits. Transfer through the Ngorongoro Conservation area with a brief stop at the Crater rim viewpoint. Arrive at your tented camp as the sun sets over the savannah.', '["Airport transfer","Ngorongoro rim viewpoint stop","Welcome briefing","Dinner at camp"]', '"Dinner"', 'Luxury tented camp, Serengeti'),
(1, 2, 'Southern Serengeti — Great Migration Herds', 'Rise before dawn for a sunrise game drive. The southern Serengeti plains are teeming with wildebeest, zebras, and Thomson''s gazelle during calving season. Afternoon drive to the acacia woodlands for leopard sightings. Sundowner at a scenic kopje.', '["Full-day game drive","Wildebeest herd tracking","Big cat spotting","Sundowner at kopje"]', '"Breakfast, Lunch & Dinner"', 'Luxury tented camp, Serengeti'),
(1, 3, 'Mara River Crossing — The Ultimate Spectacle', 'One of the most dramatic wildlife events on Earth. Position at strategic crossing points along the Mara River and watch thousands of wildebeest plunge into crocodile-infested waters. Evening free at camp for optional star-gazing session.', '["Mara River crossing viewing","Crocodile & hippo watching","Picnic lunch by the river","Optional night drive"]', '"Breakfast, Lunch & Dinner"', 'Luxury tented camp, Serengeti'),
(1, 4, 'Morning Drive & Departure', 'One final sunrise game drive before hot breakfast at camp. Transfer back to Arusha/Kilimanjaro for your onward journey, memories etched forever.', '["Final morning game drive","Hot breakfast at camp","Departure transfer"]', '"Breakfast"', NULL);

-- Tour 2: Masai Mara Big Five Safari (4 days)
INSERT INTO tour_itineraries (tour_id, day_number, title, description, activities, meals, accommodation) VALUES
(2, 1, 'Nairobi to Masai Mara — Flight to the Wild', 'Early morning flight from Wilson Airport to the Mara (45 minutes). Arrive at your camp, freshen up, and head straight out for an afternoon game drive. The Mara never disappoints — lions, elephant herds, and cheetah are commonly spotted on day one.', '["Wilson Airport check-in","Scenic flight over the Rift Valley","Afternoon game drive","Sundowner on the plains"]', '"Lunch & Dinner"', 'Luxury camp, Masai Mara'),
(2, 2, 'Full Day Big Five Hunt', 'A full day dedicated to tracking the Big Five — lion, leopard, elephant, buffalo, and rhino. Your Maasai guide''s knowledge of animal behavior ensures you''re always in the right place at the right time. Visit a Maasai village in the afternoon.', '["Morning & afternoon game drives","Maasai village cultural visit","Big Five tracking","Evening campfire"]', '"Breakfast, Lunch & Dinner"', 'Luxury camp, Masai Mara'),
(2, 3, 'The Mara Triangle & Predator Country', 'Cross into the Mara Triangle — a wildlife-dense zone managed by the Mara Conservancy. This area has the highest concentration of big cats in Africa. Watch the daily drama of hunts, kills, and territorial battles unfold before your eyes.', '["Mara Triangle exclusive game drive","Big cat tracking (lion, cheetah, leopard)","Balloon safari option (extra)","Bush dinner under the stars"]', '"Breakfast, Lunch & Dinner"', 'Luxury camp, Masai Mara'),
(2, 4, 'Final Dawn Drive & Fly Home', 'Last sunrise drive with the Mara''s magic light. Hot champagne breakfast at camp. Afternoon flight back to Nairobi, with a heart full of memories.', '["Dawn game drive","Bush champagne breakfast","Departure flight to Nairobi"]', '"Breakfast"', NULL);

-- Tour 7: Masai Mara Wildebeest Migration (4 days)
INSERT INTO tour_itineraries (tour_id, day_number, title, description, activities, meals, accommodation) VALUES
(7, 1, 'Fly to the Mara — Migration Country Awaits', 'Depart Nairobi''s Wilson Airport on a scenic 45-minute flight over the Great Rift Valley. Land in the heart of migration country. Afternoon game drive immediately reveals vast wildebeest herds stretching to the horizon.', '["Nairobi Wilson Airport departure","Scenic flight over Rift Valley","Afternoon migration game drive","Camp briefing by lead guide"]', '"Lunch & Dinner"', 'Premium migration camp, North Mara'),
(7, 2, 'Mara River — The Great Crossing', 'The main event. Spend the morning positioned at the most active crossing points along the Mara River. When the herds charge, the ground trembles. Nile crocodiles await. Pure drama. Afternoon recovery drive with lion and hyena tracking.', '["Mara River crossing observation (all morning)","Crocodile & hippo watching","Nile crocodile spotting","Afternoon predator game drive","Campfire stories with guides"]', '"Breakfast, Lunch & Dinner"', 'Premium migration camp, North Mara'),
(7, 3, 'Following the Herds — Plains of the Mara', 'Track the migration herds across the vast Mara ecosystem. Cheetah mothers teaching cubs to hunt, prides of lions on fresh kills, elephant families at waterholes — every hour delivers something extraordinary. Maasai village visit in the late afternoon.', '["Full-day migration tracking","Lioness & cub encounter","Cheetah coalition sighting","Maasai manyatta visit","Sunset over the Oloololo Escarpment"]', '"Breakfast, Lunch & Dinner"', 'Premium migration camp, North Mara'),
(7, 4, 'Final Dawn Safari & Return to Nairobi', 'The last golden hour in the Mara. An early drive reveals what the night left behind — fresh predator activity marks every dawn. Champagne breakfast at camp before your flight back to Nairobi.', '["Dawn predator tracking","Champagne bush breakfast","Departure flight to Nairobi Wilson"]', '"Breakfast"', NULL);

-- Tour 8: Mombasa Cultural Tour (3 days)
INSERT INTO tour_itineraries (tour_id, day_number, title, description, activities, meals, accommodation) VALUES
(8, 1, 'Arrival in Mombasa & Old Town Discovery', 'Transfer from Mombasa Moi International Airport to your Old Town boutique hotel. After freshening up, a sunset walk through the winding alleys of Old Town reveals carved Swahili doors, Arab-influenced architecture, and fragrant spice stalls. Welcome dinner of fresh seafood at a rooftop restaurant overlooking the harbor.', '["Airport transfer","Old Town introductory walk","Visit to the Old Harbour dhow anchorage","Welcome rooftop seafood dinner"]', '"Dinner"', 'Boutique hotel, Mombasa Old Town'),
(8, 2, 'Fort Jesus, Spice Markets & Swahili Cooking', 'Morning exploration of Fort Jesus — the UNESCO World Heritage Fort built by the Portuguese in 1593. Learn how this coastal stronghold changed hands nine times. After lunch, visit the bustling Kongowea spice market. Afternoon Swahili cooking class with a local chef, preparing aromatic biryani and pilau.', '["Fort Jesus guided tour","Portuguese colonial history walk","Kongowea spice market visit","Swahili cooking class","Dhow sunset cruise on the harbor"]', '"Breakfast, Lunch & Dinner"', 'Boutique hotel, Mombasa Old Town'),
(8, 3, 'Nyali Beach & Departure', 'Morning drive to Nyali Beach for a relaxed Indian Ocean swim before departure. Visit Haller Park — a former quarry transformed into a wildlife sanctuary with giraffes, hippos, and Nile crocodiles. Transfer to airport for onward journey.', '["Nyali Beach morning swim","Haller Park wildlife sanctuary visit","Departure transfer to airport"]', '"Breakfast"', NULL);

-- Tour 9: Diani Beach Escape (5 days)
INSERT INTO tour_itineraries (tour_id, day_number, title, description, activities, meals, accommodation) VALUES
(9, 1, 'Arrive Diani — First Steps on Paradise', 'Fly from Nairobi to Ukunda Airstrip (40 minutes) or transfer from Mombasa. Check in to your beach resort and spend the rest of the day adapting to paradise — the Indian Ocean lapping at white sand just steps from your room. Welcome sundowner at the beach bar.', '["Ukunda Airport arrival transfer","Resort check-in","Private beach relaxation","Welcome cocktail at sundowner"]', '"Dinner"', 'Premium beach resort, Diani'),
(9, 2, 'Kisite Marine Park — Snorkelling & Dolphins', 'Full-day boat excursion to Kisite Mpunguti Marine Park — one of Kenya''s best snorkelling spots. Encounter spinner dolphins en route, snorkel vibrant coral gardens, and have a BBQ lunch on Wasini Island. Afternoon free for beach volleyball, kayaking, or relaxation.', '["Dhow boat to Kisite Marine Park","Dolphin watching","Snorkelling in coral gardens","Wasini Island BBQ lunch","Afternoon free beach time"]', '"Breakfast, Lunch & Dinner"', 'Premium beach resort, Diani'),
(9, 3, 'Colobus Forest Walk & Deep-Sea Fishing', 'Morning guided walk through the Ngumba Island Colobus Trust forest — watching rare black-and-white colobus monkeys at eye level. Afternoon deep-sea fishing charter for marlin, kingfish, and barracuda (optional). Sunset Swahili seafood BBQ on the beach.', '["Colobus monkey forest walk","Deep-sea fishing charter (optional)","Village interaction tour","Sundowner beach BBQ"]', '"Breakfast, Lunch & Dinner"', 'Premium beach resort, Diani'),
(9, 4, 'Shimba Hills Day Trip — Elephants & Waterfalls', 'Half-day excursion to Shimba Hills National Reserve — the only coastal elephant habitat in Kenya. Home to sable antelope and stunning Sheldrick Falls. Return to Diani for a relaxed afternoon and farewell dinner.', '["Shimba Hills game drive","Sable antelope sighting","Sheldrick Falls walk","Farewell dinner on the beach"]', '"Breakfast, Lunch & Dinner"', 'Premium beach resort, Diani'),
(9, 5, 'Beach Morning & Departure', 'Final morning — a slow breakfast, one last swim, and a walk along the beach collecting memories. Transfer to Ukunda airstrip or Mombasa for your onward flight.', '["Final beach morning","Departure transfer"]', '"Breakfast"', NULL);

-- Tour 10: Amboseli Elephant Safari (3 days)
INSERT INTO tour_itineraries (tour_id, day_number, title, description, activities, meals, accommodation) VALUES
(10, 1, 'Nairobi to Amboseli — Kilimanjaro in Sight', 'Depart Nairobi after breakfast for the 4-hour scenic drive through Maasai lands toward Amboseli. The first glimpse of Kilimanjaro — Africa''s highest peak towering above the plains — is a moment of pure awe. Afternoon welcome game drive through the Enkongo Narok swamp.', '["Nairobi departure — scenic road transfer","First Kilimanjaro viewing stop","Afternoon swamp circuit game drive","Sundowner at Ol Tukai Lodge plains"]', '"Lunch & Dinner"', 'Lodge with Kilimanjaro view, Amboseli'),
(10, 2, 'Giants of Amboseli — Full Day Elephant Encounters', 'The day you''ll never forget. A full day tracking Amboseli''s famous elephant families — some of the largest and most studied elephants on Earth. Observe bulls, mothers with calves, and ancient matriarchs up close. Afternoon visit to Observation Hill for panoramic views of Kilimanjaro over the swamps.', '["Morning elephant family tracking","Big Five game drive","Observation Hill panoramic viewpoint","Maasai cultural village visit","Picnic lunch in the bush","Star-gazing evening program"]', '"Breakfast, Lunch & Dinner"', 'Lodge with Kilimanjaro view, Amboseli'),
(10, 3, 'Dawn Drive & Return to Nairobi', 'The magic hour in Amboseli — elephants silhouetted against dawn-lit Kilimanjaro. One final dramatic game drive before the journey back to Nairobi, arriving by early afternoon for onward connections.', '["Pre-dawn elephant silhouette game drive","Hot breakfast at lodge","Departure drive to Nairobi (arriving ~1pm)"]', '"Breakfast"', NULL);

SELECT CONCAT('Itineraries inserted: ', COUNT(*)) as status FROM tour_itineraries;
