// Static fallback data used when the backend API is unavailable (e.g. Vercel without backend)

export const STATIC_DESTINATIONS = {
  'masai-mara': {
    id: 1, slug: 'masai-mara', name: 'Masai Mara', country: 'Kenya',
    tagline: 'Witness the greatest wildlife spectacle on Earth',
    description: `The Masai Mara National Reserve is Kenya's most celebrated wildlife destination and one of the most famous game reserves in the world. Covering 1,510 km² of open savannah in south-western Kenya, the Mara forms the northern extension of Tanzania's Serengeti ecosystem.\n\nThe reserve is world-famous for the Great Wildebeest Migration — between July and October each year, over 1.5 million wildebeest, zebras, and gazelles thunder across the Mara River in one of nature's most dramatic spectacles. But the Mara is magnificent year-round, with some of Africa's highest densities of lion, leopard, cheetah, elephant, and buffalo.\n\nStay in a luxury tented camp or classic lodge under skies dazzling with stars. Rise before dawn for golden-hour game drives. Share sundowners with your guide as the savannah turns amber. The Masai Mara is not just a destination — it's a life-changing encounter with wild Africa.`,
    best_time_to_visit: 'July to October for the Great Migration river crossings. Year-round for big cats and general wildlife. November to June offers lush green scenery and fewer crowds.',
    cover_image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&q=85',
    tour_count: 8,
  },
  'serengeti-national-park': {
    id: 2, slug: 'serengeti-national-park', name: 'Serengeti', country: 'Tanzania',
    tagline: 'Where the wild things roam — endless plains, endless wonder',
    description: `The Serengeti National Park is Tanzania's oldest and most famous park, covering approximately 14,763 km² of untouched wilderness. Together with the Masai Mara it forms one continuous ecosystem — the greatest wildlife theatre on the planet.\n\nThe Serengeti is synonymous with the Great Migration: 1.5 million wildebeest and 300,000 zebra following the rains in an endless circle of life. Witness dramatic river crossings, hunting prides of lion, cheetahs sprinting across golden plains, and elephant families moving silently through the acacia forests.\n\nWith its iconic kopjes (rocky outcrops), diverse habitats, and world-class lodges and mobile camps that follow the migration, the Serengeti offers a safari experience unlike anywhere else on earth.`,
    best_time_to_visit: 'June to August for calving season and river crossings in the north. December to March for calving in the southern Serengeti. The park is superb year-round.',
    cover_image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=85',
    tour_count: 7,
  },
  'zanzibar-island': {
    id: 3, slug: 'zanzibar-island', name: 'Zanzibar Island', country: 'Tanzania',
    tagline: 'Powder-white sands, turquoise waters and Swahili soul',
    description: `Zanzibar — the Spice Island — is a semi-autonomous archipelago off the coast of Tanzania, drenched in history, culture, and natural beauty. Stone Town, the ancient heart of Zanzibar City, is a UNESCO World Heritage Site and a labyrinthine maze of narrow alleys, carved doorways, bustling bazaars, and ancient mosques.\n\nBeyond the old town lie some of the Indian Ocean's most spectacular beaches: Nungwi and Kendwa in the north with their turquoise lagoons, Paje in the east with world-class kitesurfing, and the quiet southern beaches of Jambiani for true serenity.\n\nDive the pristine coral reefs, swim with whale sharks at Mafia Island, tour the fragrant spice farms, and feast on Swahili seafood at sunset. Zanzibar is the perfect complement to any East Africa safari.`,
    best_time_to_visit: 'June to October (dry season) and December to February for sunshine and calm seas. Avoid April to May (long rains) and November (short rains).',
    cover_image: 'https://images.unsplash.com/photo-1586861203927-800a5acdcc4d?w=1200&q=85',
    tour_count: 5,
  },
  'victoria-falls': {
    id: 4, slug: 'victoria-falls', name: 'Victoria Falls', country: 'Zimbabwe',
    tagline: 'The Smoke That Thunders — one of the Seven Natural Wonders',
    description: `Victoria Falls — known locally as Mosi-oa-Tunya, "The Smoke That Thunders" — is one of the world's most spectacular natural wonders. At over 1.7km wide and 108m tall, it is the largest waterfall on earth by combined width and height.\n\nStraddling the border of Zimbabwe and Zambia, Victoria Falls is surrounded by the Zambezi National Park and offers an astonishing range of adventure activities alongside the sheer wonder of the falls themselves: white-water rafting through Batoka Gorge (one of the world's best), bungee jumping off the iconic bridge, sunset cruises on the Zambezi, helicopter flights over the falls, and swimming in the famous Devil's Pool right at the edge.\n\nStay in one of the beautiful colonial-era lodges, watch elephants and hippos from your veranda, and let the roar of the falling water send you to sleep. Victoria Falls is a destination that defies expectation every single time.`,
    best_time_to_visit: 'February to May for maximum water flow and the most dramatic spray. August to January for lower water, clearer views, and Devil\'s Pool swimming (September–December).',
    cover_image: 'https://images.unsplash.com/photo-1632793070527-a1bec39ec000?w=1200&q=85',
    tour_count: 4,
  },
  'cape-town': {
    id: 5, slug: 'cape-town', name: 'Cape Town', country: 'South Africa',
    tagline: 'The Mother City — mountains, ocean, wine and culture',
    description: `Cape Town is consistently rated one of the most beautiful cities in the world, and it's easy to see why. Flanked by the iconic flat-topped Table Mountain on one side and the cold Atlantic and warm Indian Oceans on the other, it is a city of staggering natural beauty and remarkable diversity.\n\nTake the cable car or hike up Table Mountain for panoramic views. Drive the spectacular Cape Peninsula to Cape Point and visit the African penguins at Boulders Beach. Explore the colourful Bo-Kaap neighbourhood, the vibrant waterfront, and the world-class museums. Then head to the Winelands — Stellenbosch, Franschhoek, and Paarl — for wine tasting among mountain vineyards.\n\nCape Town's food scene is world-class, the beaches breathtaking, and the people incredibly welcoming. From cultural city break to wilderness adventure, Cape Town does it all.`,
    best_time_to_visit: 'November to March (Cape summer) for warm, sunny beach weather. June to August for whale watching in Hermanus. The Winelands harvest is in February and March.',
    cover_image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1200&q=85',
    tour_count: 6,
  },
  'diani-beach': {
    id: 6, slug: 'diani-beach', name: 'Diani Beach', country: 'Kenya',
    tagline: "Kenya's most beautiful beach — coral reefs, white sand and swaying palms",
    description: `Diani Beach is widely considered the finest beach in Kenya and among the top beaches in the entire Indian Ocean. Located 30km south of Mombasa, the 17km stretch of white coral sand is framed by swaying palm trees, a turquoise lagoon, and a pristine coral reef just offshore.\n\nThe reef makes Diani a paradise for snorkelling, scuba diving, kitesurfing, and glass-bottom boat trips. Rare colobus monkeys swing through the coastal forest behind the beach, and dolphins are a common sight offshore. Explore the vibrant local village, the Shimba Hills National Reserve, and the ancient Shimba caves nearby.\n\nDiani offers a superb range of accommodation from boutique beach lodges to luxurious all-inclusive resorts, and a lively beach bar and restaurant scene. It is the perfect ending to a Kenyan safari — swap your bush boots for flip-flops and let the Indian Ocean work its magic.`,
    best_time_to_visit: 'July to October and January to February — dry season with sunny skies and calm seas. Ideal for diving, snorkelling, and kitesurfing. Avoid April to June (long rains).',
    cover_image: 'https://images.unsplash.com/photo-1559628233-100c798642c5?w=1200&q=85',
    tour_count: 4,
  },
  'mombasa-coast': {
    id: 7, slug: 'mombasa-coast', name: 'Mombasa Coast', country: 'Kenya',
    tagline: "Kenya's port city — ancient Swahili history meets the Indian Ocean",
    description: `Mombasa is Kenya's second-largest city and its most important port, sitting on a coral island connected to the mainland by causeway and ferry. It is a city of extraordinary cultural richness — Arab, Portuguese, British and African influences woven into every alleyway and architectural detail.\n\nThe old town is a UNESCO-listed treasure: Fort Jesus, built by the Portuguese in 1593, guards the harbour entrance. The narrow streets of the old town are lined with elaborately carved Arab doors, mosques, and Hindu temples. The lively Biashara Street market overflows with textiles, crafts, and the scent of spices.\n\nMombasa's northern beaches — Nyali, Bamburi, and Shanzu — are a short tuk-tuk ride from town and offer calm, warm Indian Ocean swimming. South of the island lie Likoni and the start of the beautiful South Coast, leading down to Diani. Mombasa is culture, energy, history, and an impossibly warm welcome.`,
    best_time_to_visit: 'October to March for warm, dry weather ideal for beach and sightseeing. July to September is also good with lower humidity. Avoid April to June (main rains).',
    cover_image: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=1200&q=85',
    tour_count: 4,
  },
  'amboseli': {
    id: 8, slug: 'amboseli', name: 'Amboseli', country: 'Kenya',
    tagline: 'Elephants beneath Kilimanjaro — Africa\'s most iconic image',
    description: `Amboseli National Park is one of Kenya's most popular parks, and it is easy to understand why: where else can you watch vast herds of elephant wandering against the snow-capped backdrop of Mount Kilimanjaro, Africa's highest peak?\n\nAmboseli covers 392 km² in southern Kenya on the Tanzanian border, centred on a dried-up ancient lakebed. The park is home to some of Africa's largest elephant herds and has been the site of long-term elephant research for over 50 years, meaning the animals are remarkably relaxed and habituated to vehicles — allowing extraordinary close encounters.\n\nBesides elephants, Amboseli offers excellent wildlife viewing including lion, cheetah, hyena, buffalo, giraffe, and over 600 bird species. Sundowners on the rim of the swamps with Kilimanjaro glowing pink in the last light of the day is one of Africa's most unforgettable experiences.`,
    best_time_to_visit: 'June to October and January to February for dry conditions and the clearest views of Kilimanjaro. Early mornings have the best Kilimanjaro visibility before clouds build.',
    cover_image: 'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=1200&q=85',
    tour_count: 3,
  },
  'bwindi-forest': {
    id: 9, slug: 'bwindi-forest', name: 'Bwindi Forest', country: 'Uganda',
    tagline: 'Trek into the Impenetrable Forest to meet mountain gorillas face to face',
    description: `Bwindi Impenetrable National Park in south-western Uganda is one of the most biologically diverse areas on Earth and home to roughly half of the world's remaining mountain gorillas — approximately 400 of the 800 that exist. It is a UNESCO World Heritage Site and one of the most extraordinary wildlife experiences anywhere on the planet.\n\nGorilla trekking takes you deep into the ancient montane jungle alongside expert rangers and trackers. Groups of up to eight visitors spend one magical hour in the presence of a habituated gorilla family — watching silverbacks, mothers with infants clinging to their backs, and playful juveniles tumbling through the undergrowth. It is an experience that reduces grown adults to tears.\n\nBwindi is also a paradise for birders with over 350 species including 23 Albertine Rift endemics. Combined with a visit to Rwanda's Rwanda Volcanoes National Park or Uganda's Queen Elizabeth National Park for classic savannah safari, a Bwindi gorilla trek creates the ultimate Africa adventure.`,
    best_time_to_visit: 'Year-round — gorillas can be tracked in all seasons. June to August and December to February (drier months) offer better hiking conditions. Permits must be booked far in advance.',
    cover_image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=1200&q=85',
    tour_count: 3,
  },
};

export const STATIC_TOURS = {
  'masai-mara-wildebeest-migration': {
    id: 1, slug: 'masai-mara-wildebeest-migration',
    title: 'Masai Mara Wildebeest Migration Safari',
    category: 'safari', duration_days: 7, price_per_person: 2400, price_child: 1700,
    destination_name: 'Masai Mara', country: 'Kenya', max_group_size: 8, difficulty: 'easy',
    rating_avg: 4.9, review_count: 124,
    cover_image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&q=85',
    images: ['https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&q=85','https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=85','https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=1200&q=85'],
    description: 'Experience the most breathtaking wildlife spectacle on Earth — 1.5 million wildebeest, zebras, and gazelles thundering across the Mara River. Seven days of extraordinary game drives, luxury tented camps under star-filled skies, and intimate encounters with the Masai Mara\'s legendary big cats.',
    inclusions: ['Professional expert safari guide (English-speaking)','Airport/lodge transfers in 4WD safari vehicle','All national park and conservancy entrance fees','7 nights in luxury tented camps (full board)','All meals — breakfast, lunch & dinner throughout','Bottled water on all game drives','24/7 WildSmiles in-country emergency support','Pre-departure trip briefing pack'],
    exclusions: ['International flights to/from Nairobi','Kenya visa fees ($51 — obtainable on arrival)','Travel and medical insurance (mandatory)','Gratuities for guides and camp staff','Premium spirits and champagne','Optional balloon safari ($450/person)','Personal shopping and souvenirs'],
    itinerary: [
      { day_number: 1, title: 'Nairobi Arrival & Transfer to the Mara', description: 'Arrive at Jomo Kenyatta International Airport and meet your WildSmiles representative. Transfer to Wilson Airport for a scenic 45-minute flight over the Great Rift Valley to the Masai Mara. Check into your luxury tented camp, enjoy a leisurely lunch, and take an afternoon introductory game drive — your first glimpse of the Mara\'s vast herds. Welcome dinner under the stars.', meals: 'Lunch & Dinner', accommodation: 'Luxury tented camp, Masai Mara' },
      { day_number: 2, title: 'Full Day Game Drives — Big Cat Territory', description: 'Rise before dawn for a golden-hour game drive — the hour when cheetahs hunt, leopards return from night raids, and lion prides are most active. Return for brunch then rest during the midday heat. An afternoon drive explores the Mara\'s famous big cat areas — the Mara Triangle and Rhino Ridge — as the day cools and predators become active again. Sundowners on the plains.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Luxury tented camp' },
      { day_number: 3, title: 'The Great Migration — River Crossing', description: 'Today is dedicated to the river crossing — the most dramatic moment of the Migration. Your guide will position you at the optimal crossing point as hundreds of thousands of wildebeest plunge into the crocodile-filled Mara River, scramble up the far bank, and surge across the Mara plains. A once-in-a-lifetime sight that never fails to overwhelm even the most seasoned safari-goer.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Luxury tented camp' },
      { day_number: 4, title: 'Masai Cultural Village & Afternoon Drive', description: 'Morning game drive targeting the Northern Conservancy — prime leopard territory. After lunch, visit an authentic Masai village to meet the moran warriors, see a traditional homestead (enkiama), witness the jumping dance, and learn about Masai culture, beadwork, and pastoralism. Return for sunset over the Mara with the distant silhouettes of acacia trees against an orange sky.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Luxury tented camp' },
      { day_number: 5, title: 'Full Day Exploration — Southern Mara', description: 'A full day in the southern Mara — packed lunch in the vehicle so you can stay in the field and maximise your game time. The southern Mara is often where the bulk of the Migration herds congregate and where cheetah density is highest. Today you also have the option of an optional hot air balloon safari at dawn — a magical 90-minute flight over the plains followed by a bush champagne breakfast.', meals: 'Breakfast (packed lunch), Dinner', accommodation: 'Luxury tented camp' },
      { day_number: 6, title: 'Guided Bush Walk & Sundowner Drive', description: 'Start the day differently — a guided walking safari with your armed ranger guide. Walking in the Mara gives you a completely different perspective, tuning your senses to the smaller details: tracks, dung, insects, plants the Masai use for medicine. Afternoon drive targeting the Mara River for a last chance to see a crossing. Farewell sundowners and camp fire dinner with your guide sharing stories of the bush.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Luxury tented camp' },
      { day_number: 7, title: 'Final Morning Drive & Departure', description: 'One last early morning drive to say farewell to the Mara\'s wild residents. Return to camp for a late breakfast before your light aircraft flight back to Nairobi. Transfer to JKIA for your onward international flight, or continue on extension to Amboseli, Zanzibar, or the Kenyan coast. Tour ends with memories that will last a lifetime.', meals: 'Breakfast', accommodation: null },
    ],
  },
  'serengeti-great-migration': {
    id: 2, slug: 'serengeti-great-migration',
    title: 'Serengeti Great Migration Safari',
    category: 'safari', duration_days: 8, price_per_person: 2800, price_child: 2000,
    destination_name: 'Serengeti', country: 'Tanzania', max_group_size: 8, difficulty: 'easy',
    rating_avg: 4.9, review_count: 210,
    cover_image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=85',
    images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=85','https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&q=85'],
    description: 'Follow the 1.5 million wildebeest on their epic annual journey across Tanzania\'s boundless Serengeti plains. Eight days of extraordinary wildlife encounters, mobile bush camps that follow the herds, and the raw, untamed magic of one of Africa\'s last great wilderness areas.',
    inclusions: ['Expert Swahili/English guide','All park and conservancy fees','Flights Arusha–Serengeti–Arusha','8 nights mobile luxury camp (full board)','All meals and beverages (non-premium)','4WD safari vehicle (exclusive to your group)','WildSmiles 24/7 support'],
    exclusions: ['International flights','Tanzania visa ($50)','Travel insurance','Gratuities','Premium drinks','Balloon safari (optional, $500)'],
    itinerary: [
      { day_number: 1, title: 'Arusha Arrival & Briefing', description: 'Fly into Kilimanjaro International Airport and transfer to Arusha. Meet your WildSmiles guide for a full safari briefing over dinner. Equipment check and overnight in Arusha before the early morning flight to the Serengeti.', meals: 'Dinner', accommodation: 'Arusha lodge' },
      { day_number: 2, title: 'Fly to Serengeti — First Game Drives', description: 'Early morning flight to Seronera airstrip at the heart of the Serengeti. Transfer straight into the field — your first game drive begins immediately. Search for lion, leopard and cheetah in the central Serengeti woodlands and kopjes. Settle into your luxury mobile camp as the sunset paints the plains gold.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Mobile luxury camp' },
      { day_number: 3, title: 'Following the Migration Herds', description: 'Long day in the field tracking the migration herds. Depending on the season your camp will have repositioned to put you right in the heart of the action — whether calving in the south, river crossings in the west, or the great northward push. Packed lunch in the vehicle maximises time with wildlife.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Mobile luxury camp' },
      { day_number: 4, title: 'Predator Plains — Lions & Cheetah', description: 'Focus on the Serengeti\'s incredible predator density today. The open plains are perfect cheetah country — watch them hunt at full sprint with the herd thundering behind. Lion prides lounging on kopjes, hyenas at kills, and the ever-present vultures circling overhead. A full, incredible day.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Mobile luxury camp' },
      { day_number: 5, title: 'Balloon Safari & Bush Breakfast', description: 'Before dawn, board your hot air balloon for a 90-minute float over the waking Serengeti — wildebeest below, the rising sun ahead. Land in the bush for a beautifully laid champagne breakfast. Afternoon game drive and early return to camp for laundry, spa, and photography review with your guide.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Mobile luxury camp' },
      { day_number: 6, title: 'Grumeti River & Western Corridor', description: 'Transfer to the Western Corridor — the Grumeti River stage of the Migration where enormous crocodiles lie in wait. The crossings here are fierce and fast. Excellent birding in the riverine forest, hippo pools, and the chance of seeing the elusive African wild dog.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Mobile luxury camp' },
      { day_number: 7, title: 'Ngorongoro Crater Descent', description: 'Transfer south to the Ngorongoro Crater — the world\'s largest intact caldera and a natural enclosure for extraordinary concentrations of wildlife including the endangered black rhino. A full day inside the crater: close encounters with rhino, elephant, flamingo-fringed lakes, and dense lion prides. Overnight on the crater rim.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Crater rim lodge' },
      { day_number: 8, title: 'Farewell Morning & Departure', description: 'Final breakfast on the crater rim with sweeping views over the caldera. Transfer to Arusha or Kilimanjaro airport for your onward journey. Depart Tanzania with memories of one of the greatest wildlife spectacles on Earth.', meals: 'Breakfast', accommodation: null },
    ],
  },
  'zanzibar-beach-retreat': {
    id: 3, slug: 'zanzibar-beach-retreat',
    title: 'Zanzibar Spice Island Beach Retreat',
    category: 'beach', duration_days: 5, price_per_person: 1200, price_child: 800,
    destination_name: 'Zanzibar', country: 'Tanzania', max_group_size: 12, difficulty: 'easy',
    rating_avg: 4.8, review_count: 98,
    cover_image: 'https://images.unsplash.com/photo-1586861203927-800a5acdcc4d?w=1200&q=85',
    images: ['https://images.unsplash.com/photo-1586861203927-800a5acdcc4d?w=1200&q=85'],
    description: 'Escape to the Indian Ocean\'s most enchanting island. White coral sands, turquoise reefs alive with tropical fish, the labyrinthine streets of UNESCO-listed Stone Town, fragrant spice farms, and the legendary Swahili hospitality of Zanzibar await you.',
    inclusions: ['5 nights beach boutique hotel (full board)','Stone Town guided cultural walking tour','Half-day spice farm tour','Snorkelling trip on the coral reef','Dhow sunset cruise','Airport/hotel transfers','Welcome kit with beach bag and essentials'],
    exclusions: ['International and domestic flights','Tanzania visa','Travel insurance','Scuba diving courses (bookable locally)','Kitesurfing lessons','Gratuities'],
    itinerary: [
      { day_number: 1, title: 'Arrival in Stone Town', description: 'Fly into Zanzibar International Airport and transfer to your boutique hotel on the north or east coast. If arriving in the afternoon, a guide will show you the highlights of Stone Town before sunset — the House of Wonders, Forodhani night food market, and the old Arab Fort. Welcome Swahili seafood dinner.', meals: 'Dinner', accommodation: 'Beach boutique hotel' },
      { day_number: 2, title: 'Stone Town Culture & Spice Farm', description: 'Morning guided walking tour of Stone Town: the Slave Monument, Anglican Cathedral, Palace Museum, and the legendary carved wooden doors. After lunch, a half-day tour of a working spice farm — smell, taste and identify cloves, cardamom, nutmeg, vanilla, and cinnamon growing in their natural environment. Back at the resort for sundowners.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Beach boutique hotel' },
      { day_number: 3, title: 'Coral Reef Snorkelling & Mnemba Island', description: 'Board your traditional wooden dhow for a morning trip to the world-class coral reefs of Mnemba Atoll — one of East Africa\'s finest marine environments. Snorkel among sea turtles, dolphins, parrotfish, and colourful reef fish. Return to the resort by early afternoon. Rest, swim, or take a windsurfing lesson in the lagoon.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Beach boutique hotel' },
      { day_number: 4, title: 'Free Beach Day & Dhow Sunset Cruise', description: 'Today is yours — laze on the powder-white beach, try your hand at kitesurfing, take a bicycle to the local fishing village, or simply read under a palm tree. As the sun descends, board a traditional dhow for a magical 2-hour sunset cruise along the coastline, cocktails in hand, listening to traditional Swahili music.', meals: 'Breakfast & Dinner', accommodation: 'Beach boutique hotel' },
      { day_number: 5, title: 'Farewell Morning & Departure', description: 'Final breakfast looking out over the Indian Ocean. Last chance for a morning swim in the turquoise lagoon before your transfer to Zanzibar airport. Depart with a tan, spice-scented memories, and the warm glow of an island that gives itself so generously to its visitors.', meals: 'Breakfast', accommodation: null },
    ],
  },
  'victoria-falls-adventure': {
    id: 4, slug: 'victoria-falls-adventure',
    title: 'Victoria Falls Adventure & Rafting',
    category: 'adventure', duration_days: 4, price_per_person: 1600, price_child: 1100,
    destination_name: 'Victoria Falls', country: 'Zimbabwe', max_group_size: 10, difficulty: 'moderate',
    rating_avg: 4.8, review_count: 76,
    cover_image: 'https://images.unsplash.com/photo-1632793070527-a1bec39ec000?w=1200&q=85',
    images: ['https://images.unsplash.com/photo-1632793070527-a1bec39ec000?w=1200&q=85'],
    description: 'Stand at the edge of The Smoke That Thunders — Victoria Falls, the largest waterfall on Earth. Four adrenaline-charged days of white-water rafting through Batoka Gorge, bungee jumping, helicopter flights, sunset cruises, and elephant encounters in the wild.',
    inclusions: ['4 nights lodge accommodation (full board)','Entry to Victoria Falls National Park (both sides)','White-water rafting (Grade 5) Batoka Gorge','Sunset Zambezi cruise','Airport/hotel transfers','Park activities guide'],
    exclusions: ['Flights','Zimbabwe/Zambia visa','Bungee jump (optional)','Helicopter flight (optional)','Travel insurance','Gratuities'],
    itinerary: [
      { day_number: 1, title: 'Arrival & First View of the Falls', description: 'Arrive at Victoria Falls Airport and transfer to your lodge. After settling in, walk the short distance through rainforest to your first view of the falls — the spray hits you before you see them, and then suddenly 1.7km of thundering white water fills your entire vision. Sundowner cruise on the Zambezi as elephants wade across upstream.', meals: 'Lunch & Dinner', accommodation: 'Victoria Falls Lodge' },
      { day_number: 2, title: 'Batoka Gorge White-Water Rafting', description: 'The Batoka Gorge is consistently rated among the world\'s top white-water experiences. Your day begins with a safety briefing before descending into the gorge for a full day of Grade 4-5 rapids — the \'Stairway to Heaven\', the \'Washing Machine\', and the legendary \'Commercial Suicide\'. Exhilarating, exhausting, and completely unforgettable.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Victoria Falls Lodge' },
      { day_number: 3, title: 'Falls Exploration & Livingstone Island', description: 'Walk the entire length of the falls with your guide, crossing to the Zambia side for a different perspective. Brave souls can swim in Devil\'s Pool right on the edge of the main falls (seasonal, Sep–Dec). Optional bungee jump from the 111m Victoria Falls Bridge. Evening game walk in the surrounding national park — elephants, buffalo, and giraffe are common.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Victoria Falls Lodge' },
      { day_number: 4, title: 'Morning Helicopter Flight & Departure', description: 'Rise early for the \'Flight of Angels\' — a thrilling 15-minute helicopter flight over the falls that explains why Livingstone called it the most beautiful sight he ever beheld. Return to the lodge for a final breakfast before your transfer to the airport. Tour ends — the roar of the falls will echo in your ears for years to come.', meals: 'Breakfast', accommodation: null },
    ],
  },
  'cape-town-explorer': {
    id: 5, slug: 'cape-town-explorer',
    title: 'Cape Town Explorer & Winelands Tour',
    category: 'city', duration_days: 6, price_per_person: 1900, price_child: 1300,
    destination_name: 'Cape Town', country: 'South Africa', max_group_size: 10, difficulty: 'easy',
    rating_avg: 4.9, review_count: 152,
    cover_image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1200&q=85',
    images: ['https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1200&q=85'],
    description: 'The Mother City in all her glory — Table Mountain, the Cape Peninsula, penguin colonies, the Winelands, vibrant food scenes, and world-class beaches. Six days to fall completely in love with Cape Town.',
    inclusions: ['6 nights boutique hotel Cape Town (bed & breakfast)','Table Mountain cable car (weather permitting)','Cape Peninsula full day tour','Winelands day tour (Stellenbosch & Franschhoek)','Boulders Penguin Colony entry','Airport/hotel transfers'],
    exclusions: ['Flights','South Africa visa (most countries visa-free)','Travel insurance','Lunch & dinners (except specified)','Gratuities','Optional shark cage diving'],
    itinerary: [
      { day_number: 1, title: 'Cape Town Arrival & Waterfront', description: 'Arrive at Cape Town International and transfer to your hotel in the city. After freshening up, head to the V&A Waterfront for your first Table Mountain views, browse the craft markets and galleries, and choose from Cape Town\'s world-class restaurants for a welcome dinner. The city gleams.', meals: 'Dinner (welcome)', accommodation: 'Cape Town boutique hotel' },
      { day_number: 2, title: 'Table Mountain & City Bowl', description: 'Take the revolving cable car to the flat top of Table Mountain for 360° views of the city, ocean, and Cape Peninsula stretching south. Afternoon exploring the City Bowl — Bo-Kaap\'s colourful houses and Cape Malay culture, the Company\'s Garden, the South African Museum, and a walk through the creative arts precinct of De Waterkant.', meals: 'Breakfast', accommodation: 'Cape Town boutique hotel' },
      { day_number: 3, title: 'Cape Peninsula — Penguins & Cape Point', description: 'Full day driving the spectacular Cape Peninsula — one of the world\'s greatest coastal drives. Visit Boulders Beach to walk among 3,000 African penguins, stand at the dramatic cliffs of Cape Point at the continent\'s southern tip, and stop at the colourful working fishing harbour of Kalk Bay for fresh snoek and chips.', meals: 'Breakfast', accommodation: 'Cape Town boutique hotel' },
      { day_number: 4, title: 'Stellenbosch & Franschhoek Winelands', description: 'Drive into the Winelands — the Cape\'s wine country — through mountain passes and valleys of vineyards. Visit three of Stellenbosch\'s top estates for wine and cheese pairings. Lunch in the French-influenced village of Franschhoek, the gourmet capital of South Africa. Return to Cape Town via the Helshoogte Pass as the late afternoon sun turns the mountains to flame.', meals: 'Breakfast, Lunch', accommodation: 'Cape Town boutique hotel' },
      { day_number: 5, title: 'Free Day — Beach & Creative Cape Town', description: 'Today explore at your own pace. Swim at Clifton or Camp\'s Bay beaches with their dramatic mountain backdrop. Visit the Zeitz Museum of Contemporary Art Africa — the most significant contemporary art museum on the continent — housed in a converted silo. Shop for high-end African design at the Old Biscuit Mill Saturday market (if applicable). Final dinner in the city — let your guide recommend the best table in town.', meals: 'Breakfast', accommodation: 'Cape Town boutique hotel' },
      { day_number: 6, title: 'Farewell Morning & Departure', description: 'Final breakfast with Table Mountain views. Transfer to Cape Town International for your onward journey. The Mother City never quite lets you go — you will be planning your return before you even board your flight.', meals: 'Breakfast', accommodation: null },
    ],
  },
  'amboseli-elephant-safari': {
    id: 6, slug: 'amboseli-elephant-safari',
    title: 'Amboseli Elephant Safari & Kilimanjaro Views',
    category: 'safari', duration_days: 5, price_per_person: 1800, price_child: 1300,
    destination_name: 'Amboseli', country: 'Kenya', max_group_size: 8, difficulty: 'easy',
    rating_avg: 4.8, review_count: 88,
    cover_image: 'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=1200&q=85',
    images: ['https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=1200&q=85'],
    description: 'Watch Africa\'s largest elephant herds roam beneath the snow-capped peak of Mount Kilimanjaro. Amboseli offers some of the most intimate elephant encounters in the world, combined with excellent big cat sightings and the most iconic views on the continent.',
    inclusions: ['5 nights Amboseli lodge (full board)','All park entry fees','Game drives morning & afternoon','Professional guide','Bush sundowners','Airport/lodge transfers (4WD)','24/7 WildSmiles support'],
    exclusions: ['International flights','Kenya visa','Travel insurance','Gratuities','Premium drinks','Optional Masai village visit ($30)'],
    itinerary: [
      { day_number: 1, title: 'Nairobi to Amboseli', description: 'Depart Nairobi by road through the highlands, arriving at Amboseli by late morning. Check into your lodge with Kilimanjaro as your permanent backdrop. After lunch, afternoon game drive through the swamps where elephant families come to drink — Kilimanjaro glowing in the late afternoon light. Welcome campfire dinner.', meals: 'Lunch & Dinner', accommodation: 'Amboseli lodge' },
      { day_number: 2, title: 'Elephant Herds & Big Cats', description: 'Early morning game drive when the air is crisp and Kilimanjaro is at its clearest. Amboseli\'s elephant research history means the herds are remarkably relaxed — bulls with enormous tusks walk within metres of your vehicle. Afternoon drive along the swamp edges searching for lion, cheetah, and the park\'s large buffalo herds.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Amboseli lodge' },
      { day_number: 3, title: 'Full Day Exploration & Bush Lunch', description: 'A full day in the park with a packed bush lunch at a scenic picnic site in the shadow of Kilimanjaro. The middle of Amboseli — the dry ancient lake bed — supports extraordinary concentrations of wildlife when the dust devils are still. Afternoon focus on birds — over 600 species including the spectacular crowned crane and saddle-billed stork.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Amboseli lodge' },
      { day_number: 4, title: 'Masai Cultural Experience & Sunset Drive', description: 'Morning game drive followed by an optional visit to an authentic Masai boma — meet the community, see traditional homesteads, and understand the ancient cattle-herding culture that has coexisted with Amboseli\'s wildlife for centuries. Afternoon drive targeting the swamps at golden hour when elephant families gather in their hundreds.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Amboseli lodge' },
      { day_number: 5, title: 'Final Dawn Drive & Departure', description: 'One last early game drive — Kilimanjaro at dawn is a sight worth setting an alarm for. Return to the lodge for a full breakfast before the drive back to Nairobi, arriving early afternoon in time for onward connections or a Nairobi city tour before your flight.', meals: 'Breakfast', accommodation: null },
    ],
  },
  'mombasa-cultural-tour': {
    id: 7, slug: 'mombasa-cultural-tour',
    title: 'Mombasa Cultural Heritage & Coast Tour',
    category: 'cultural', duration_days: 4, price_per_person: 950, price_child: 650,
    destination_name: 'Mombasa', country: 'Kenya', max_group_size: 12, difficulty: 'easy',
    rating_avg: 4.7, review_count: 64,
    cover_image: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=1200&q=85',
    images: ['https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=1200&q=85'],
    description: 'Dive into a thousand years of Swahili history along Kenya\'s coast. Portuguese forts, Arab mosques, colourful old town markets, dhow harbours, and the legendary warmth of coastal Kenyan hospitality — all wrapped around Indian Ocean beach days.',
    inclusions: ['4 nights coastal hotel (half board)','Fort Jesus guided tour','Old Town walking tour','Haller Park nature reserve visit','Dhow harbour boat trip','Airport/hotel transfers'],
    exclusions: ['Flights','Kenya visa','Travel insurance','Lunches (except day 2)','Gratuities'],
    itinerary: [
      { day_number: 1, title: 'Mombasa Arrival & Old Town Introduction', description: 'Arrive at Moi International Airport and transfer to your coastal hotel. After lunch, your guide introduces you to the warren of Mombasa Old Town — the Mackinnon Market, the four historic tusks on Moi Avenue, and a walk through the old Arab quarter before the call to prayer echoes from the Mandhry Mosque. Swahili seafood dinner at a harbour restaurant.', meals: 'Dinner', accommodation: 'Mombasa Coast hotel' },
      { day_number: 2, title: 'Fort Jesus & Swahili History', description: 'Spend the morning inside Fort Jesus, the extraordinary 16th-century Portuguese fortress that guarded the Mombasa harbour for three centuries. Your guide brings to life the fort\'s remarkable history of Arab, Portuguese, Omani, and British occupation. Afternoon free for Old Town exploration — negotiate for kangas, kikois, and spices in the Biashara Street market. Traditional Swahili cooking demonstration and dinner.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Mombasa Coast hotel' },
      { day_number: 3, title: 'Haller Park, Dhow Harbour & Beaches', description: 'Morning visit to Haller Park — a remarkable ecological restoration project that transformed a wasteland quarry into a thriving wildlife sanctuary, home to hippos, giraffe, buffalo, and giant tortoises. Afternoon traditional dhow boat trip in the harbour, watching fishermen mend nets and the old dhows that still make the annual run to the Persian Gulf. Free evening at your beach resort.', meals: 'Breakfast & Dinner', accommodation: 'Mombasa Coast hotel' },
      { day_number: 4, title: 'Nyali Beach & Departure', description: 'Morning at leisure on Nyali Beach — swim in the warm Indian Ocean, take a final stroll through the local fishing village, collect last gifts from the beachside craft stalls. Transfer to the airport for your onward journey, the smell of sea salt and spice still on your skin.', meals: 'Breakfast', accommodation: null },
    ],
  },
  'diani-beach-escape': {
    id: 8, slug: 'diani-beach-escape',
    title: "Diani Beach Escape — Kenya's South Coast",
    category: 'beach', duration_days: 5, price_per_person: 1100, price_child: 750,
    destination_name: 'Diani Beach', country: 'Kenya', max_group_size: 12, difficulty: 'easy',
    rating_avg: 4.8, review_count: 72,
    cover_image: 'https://images.unsplash.com/photo-1559628233-100c798642c5?w=1200&q=85',
    images: ['https://images.unsplash.com/photo-1559628233-100c798642c5?w=1200&q=85'],
    description: 'Seventeen kilometres of white coral sand, a turquoise lagoon, pristine coral reefs, and colobus monkeys swinging through the coastal forest — Diani Beach is Kenya\'s most beautiful coastline and the perfect Indian Ocean escape after a Kenyan safari.',
    inclusions: ['5 nights Diani beach resort (full board)','Half-day snorkelling trip on the reef','Colobus monkey sanctuary guided walk','Glass-bottom boat ride','Airport/hotel transfers','Welcome pack'],
    exclusions: ['Flights','Kenya visa','Travel insurance','Scuba diving (bookable locally)','Kitesurfing lessons (bookable locally)','Gratuities'],
    itinerary: [
      { day_number: 1, title: 'Arrival at Diani', description: 'Fly into Ukunda Airstrip (15 minutes from Mombasa) or transfer by road from Mombasa. Check into your beachfront resort, change into your swimsuit, and put your feet in the Indian Ocean. Welcome Swahili dinner as the dhows sail past in the sunset.', meals: 'Dinner', accommodation: 'Diani beach resort' },
      { day_number: 2, title: 'Coral Reef Snorkelling', description: 'Morning snorkelling trip over the Diani coral reef — your guide takes you to the best spots to find green turtles, octopus, moray eels, and schools of neon reef fish. Back to the resort for lunch and afternoon at leisure on the beach. Sunset beach bar with local musicians.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Diani beach resort' },
      { day_number: 3, title: 'Colobus Sanctuary & Village Visit', description: 'Morning guided walk at the Colobus Conservation sanctuary — see the rare Angolan colobus monkeys in their coastal forest habitat, understand conservation challenges, and learn about local ecology. Afternoon glass-bottom boat ride over the lagoon. Evening visit to the local village market for fresh produce and crafts.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Diani beach resort' },
      { day_number: 4, title: 'Free Day — Water Sports & Relaxation', description: 'The day is entirely yours. Try kitesurfing on the flat water inside the reef (world-class conditions), take a paddleboard out at dawn, or simply move your sun lounger between the pool and the beach. Farewell dinner at the resort\'s beachfront restaurant — fresh lobster, grilled fish, and watching the stars appear over the Indian Ocean.', meals: 'Breakfast & Dinner', accommodation: 'Diani beach resort' },
      { day_number: 5, title: 'Final Morning & Departure', description: 'Last swim in the Indian Ocean. Collect your shells, say farewell to the beach boys and kitchen staff who have looked after you so well, and transfer to Ukunda Airstrip or Mombasa for your onward flight. Diani stays with you long after you leave.', meals: 'Breakfast', accommodation: null },
    ],
  },
  'bwindi-gorilla-trekking': {
    id: 9, slug: 'bwindi-gorilla-trekking',
    title: 'Bwindi Gorilla Trekking Experience',
    category: 'wildlife', duration_days: 5, price_per_person: 3200, price_child: 2400,
    destination_name: 'Bwindi Forest', country: 'Uganda', max_group_size: 8, difficulty: 'challenging',
    rating_avg: 5.0, review_count: 89,
    cover_image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=1200&q=85',
    images: ['https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=1200&q=85'],
    description: 'Once in a lifetime. Trek into Uganda\'s ancient Bwindi Impenetrable Forest to spend one extraordinary hour in the presence of a mountain gorilla family. Silverbacks, mothers with infants, juveniles at play — a face-to-face encounter that will fundamentally change how you see the world.',
    inclusions: ['Mountain gorilla trekking permit ($700 included)','4 nights Bwindi lodge (full board)','Expert tracker-guides','Porters for the trek (highly recommended)','All park entrance fees','Flights Entebbe–Kihihi–Entebbe','Airport/lodge transfers','WildSmiles pre-trek briefing pack'],
    exclusions: ['International flights to Entebbe','Uganda visa ($50)','Travel insurance','Gratuities for trackers, rangers and porters','Premium drinks','Optional second gorilla trek ($700, permit subject to availability)'],
    itinerary: [
      { day_number: 1, title: 'Entebbe Arrival & briefing', description: 'Fly into Entebbe International Airport. Transfer to your Entebbe hotel for an overnight rest and full pre-expedition briefing from your WildSmiles guide. Review health guidelines, trekking requirements, and what to expect when you meet the gorillas. Early to bed — tomorrow is a flight day.', meals: 'Dinner', accommodation: 'Entebbe hotel' },
      { day_number: 2, title: 'Fly to Bwindi & Afternoon Walk', description: 'Early morning light aircraft flight from Entebbe to Kihihi airstrip at the edge of Bwindi, sweeping over Lake Victoria and the Albertine Rift. Transfer to your lodge on the forest edge. Afternoon guided nature walk through the buffer zone — bird species, forest botany, and your first glimpse into the ancient canopy. Briefing for tomorrow\'s gorilla trek.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Bwindi forest lodge' },
      { day_number: 3, title: 'Gorilla Trekking — The Main Event', description: 'Rise at dawn. After breakfast, meet your UWA ranger guides and trackers at the park gate. The trek through the impenetrable forest can take anywhere from 1 to 6 hours depending on where the gorilla family has moved overnight. When you find them, you have one precious hour. Sit quietly as silverbacks thump their chests, mothers nurse infants, and juveniles scramble overhead through the vines. Nothing prepares you for this. Nothing comes close.', meals: 'Breakfast, Packed Lunch & Dinner', accommodation: 'Bwindi forest lodge' },
      { day_number: 4, title: 'Batwa Cultural Experience & Forest Birding', description: 'Spend the morning with the Batwa pygmies — the original forest people of Bwindi, displaced when the park was gazetted in 1991 but now living on its edge. They share their ancient forest knowledge, traditional hunting techniques, and music. Afternoon guided birding walk for Bwindi\'s 23 endemic bird species including the African green broadbill and Grauer\'s warbler.', meals: 'Breakfast, Lunch & Dinner', accommodation: 'Bwindi forest lodge' },
      { day_number: 5, title: 'Final Morning & Departure', description: 'One final dawn walk on the forest edge before breakfast. Transfer to Kihihi airstrip for your light aircraft flight back to Entebbe. Connect with your international flight home — a different person than the one who arrived, carrying the memory of those ancient, intelligent eyes watching you from the undergrowth.', meals: 'Breakfast', accommodation: null },
    ],
  },
};
